//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RQuote.Server.Version2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationProduct
    {
        public int Id { get; set; }
        public Nullable<int> Quotations_Id { get; set; }
        public int ProductId { get; set; }
        public int Unit { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double Amount { get; set; }
        public double GST { get; set; }
        public double Discount { get; set; }
        public double TotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Quotation Quotation { get; set; }
    }
}
